### ISSUE TITLE
[BUG] SoloPi 第一次启动加载插件时可能失败

### ISSUE THREAD

**Issue by turtle-fly** [alipay/SoloPi#136]
**Describe the bug / 问题描述**
SoloPi 第一次启动加载时可能失败，报错如下：

    插件加载失败，原因:Failed to connect to raw.githubusercontent/com/151.101.228.133:443

**To Reproduce / 复现流程**
1. 卸载 SoloPi app
2. 重新安装：`adb install SoloPi.apk`
3. 启动 SoloPi，偶现上述报错

**Error Stack/错误堆栈**
完整日志文件：
[solopi.log](https://github.com/alipay/SoloPi/files/4059126/solopi.log)

截取了其中一行报错日志如下：

    1578995385552,2020.01.14 17:49:45.552,
    ERROR,
    SoloPi-AssetsManager,
    Download failed: Connection failed with
    request[
      {
        accept=[*/*],
        if-match=[W/"828c012d338187b10d6f92809d40ffd3fdebb177cb5a46c35693e8af69e2d15e"],
        range=[bytes=0-],
        user-agent=[FileDownloader/1.7.7]
      }
    ]
    response[
      {
        accept-ranges=[bytes, bytes],
        access-control-allow-origin=[*],
        connection=[keep-alive],
        content-length=[452],
        content-type=[text/html; charset=utf-8],
        date=[Tue, 14 Jan 2020 09:49:45 GMT],
        expires=[Tue, 14 Jan 2020 09:54:45 GMT],
        retry-after=[0],
        server=[Varnish],
        vary=[Authorization,Accept-Encoding],
        via=[1.1 varnish],
        x-cache=[MISS],
        x-cache-hits=[0], 
        x-fastly-request-id=[b72b6f6265d5358887efd94c243f5fc3ba967f3b],
        x-served-by=[cache-tyo19943-TYO],
        x-timer=[S1578995385.113235,VS0,VE1]
      }
    ] http-state[412] on task[-1262172314--1],
    which is changed after verify connection, so please try again. :
    
    java.net.SocketException: Connection failed with
      request[{accept=[*/*], if-match=[W/"828c012d338187b10d6f92809d40ffd3fdebb177cb5a46c35693e8af69e2d15e"], range=[bytes=0-], user-agent=[FileDownloader/1.7.7]}]
      response[{accept-ranges=[bytes, bytes], access-control-allow-origin=[*], connection=[keep-alive], content-length=[452], content-type=[text/html; charset=utf-8], date=[Tue, 14 Jan 2020 09:49:45 GMT], expires=[Tue, 14 Jan 2020 09:54:45 GMT], retry-after=[0], server=[Varnish], vary=[Authorization,Accept-Encoding], via=[1.1 varnish], x-cache=[MISS], x-cache-hits=[0], x-fastly-request-id=[b72b6f6265d5358887efd94c243f5fc3ba967f3b], x-served-by=[cache-tyo19943-TYO], x-timer=[S1578995385.113235,VS0,VE1]}]
    
    http-state[412] on task[-1262172314--1], which is changed after verify connection, so please try again.
    <br> 	at com.liulishuo.filedownloader.b.e.run(SourceFile:97)
    <br> 	at com.liulishuo.filedownloader.b.d.c(SourceFile:609)
    <br> 	at com.liulishuo.filedownloader.b.d.run(SourceFile:295)
    <br> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    <br> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    <br> 	at java.lang.Thread.run(Thread.java:764)
    <br>

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/3271116/72344565-893f8c80-370c-11ea-92b8-13ff6835dbc5.png)

**Device Info / 设备信息**

    "厂家":"oppo"
    "设备":"R17"
    "系统版本":"Android 8.1.0"
    "SoloPi版本":"0.10.1"
    "cpu":{
        "Processor	: AArch64 Processor rev 12 (aarch64)",
        "processor	: 0",
        "BogoMIPS	: 38.40",
        "Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp",
        "CPU implementer	: 0x51",
        "CPU architecture: 8",
        "CPU variant	: 0x7",
        "CPU part	: 0x803",
        "CPU revision	: 12",
    
        "processor	: 1",
        "BogoMIPS	: 38.40",
        "Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp",
        "CPU implementer	: 0x51",
        "CPU architecture: 8",
        "CPU variant	: 0x7",
        "CPU part	: 0x803",
        "CPU revision	: 12",
    
        "processor	: 2",
        "BogoMIPS	: 38.40",
        "Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp",
        "CPU implementer	: 0x51",
        "CPU architecture: 8",
        "CPU variant	: 0x7",
        "CPU part	: 0x803",
        "CPU revision	: 12",
    
        "processor	: 3",
        "BogoMIPS	: 38.40",
        "Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp",
        "CPU implementer	: 0x51",
        "CPU architecture: 8",
        "CPU variant	: 0x7",
        "CPU part	: 0x803",
        "CPU revision	: 12",
    
        "processor	: 4",
        "BogoMIPS	: 38.40",
        "Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp",
        "CPU implementer	: 0x51",
        "CPU architecture: 8",
        "CPU variant	: 0x7",
        "CPU part	: 0x803",
        "CPU revision	: 12",
    
        "processor	: 5",
        "BogoMIPS	: 38.40",
        "Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp",
        "CPU implementer	: 0x51",
        "CPU architecture: 8",
        "CPU variant	: 0x7",
        "CPU part	: 0x803",
        "CPU revision	: 12",
    
        "processor	: 6",
        "BogoMIPS	: 38.40",
        "Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp",
        "CPU implementer	: 0x51",
        "CPU architecture: 8",
        "CPU variant	: 0x6",
        "CPU part	: 0x802",
        "CPU revision	: 13",
    
        "processor	: 7",
        "BogoMIPS	: 38.40",
        "Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp",
        "CPU implementer	: 0x51",
        "CPU architecture: 8",
        "CPU variant	: 0x6",
        "CPU part	: 0x802",
        "CPU revision	: 13",
    
        "Hardware	: Qualcomm Technologies, Inc SDM670",
    }

**Additional context/其他内容**
失败概率蛮高的，处于相同的办公网络环境下也会偶发失败，今天的实验7次失败4次

**Comment by cathor01** [comment]
可以把仓库plugins目录下对应CPU架构的插件（有hulu_imageCompare、hulu_minicap、hulu_screenRecord、scrcpytouch四个插件，其中minicap和scrcpytouch插件不区分CPU架构）下载到手机的`/sdcard/solopi/patch/`目录下，然后在SoloPi设置里执行`导入patch目录下插件`功能
