### ISSUE TITLE
小米Redmi手机录制应用时soloPi闪退

### ISSUE THREAD

**Issue by Rain0193** [alipay/SoloPi#2]
小米设备型号：
![image](https://user-images.githubusercontent.com/31090593/59662835-51a54c00-91e0-11e9-967c-2d0a7b205943.png)

错误日志：
故障线程：main
故障日志：
java.lang.IllegalArgumentException: height must be > 0
	at android.graphics.Bitmap.checkWidthHeight(Bitmap.java:431)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:802)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:770)
	at com.alipay.hulu.service.CaseRecordManager.doAndRecordAction(SourceFile:624)
	at com.alipay.hulu.service.CaseRecordManager.operationAndRecord(SourceFile:552)
	at com.alipay.hulu.service.CaseRecordManager.processAction(SourceFile:1105)
	at com.alipay.hulu.service.CaseRecordManager$18$1.run(SourceFile:916)
	at com.alipay.hulu.common.application.LauncherApplication.a(SourceFile:208)
	at com.alipay.hulu.service.CaseRecordManager$18.a(SourceFile:912)
	at com.alipay.hulu.c.b$1$2.run(SourceFile:169)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by cathor01** [comment]
这块儿是因为在Android P的刘海屏会遮住屏幕顶端的一部分，导致Soloπ截图的高度小于实际屏幕的高度，点击底部控件时对应区域的截图为空，保留控件图片信息失败导致闪退。

**Comment by soloPi** [comment]
fixed in commit 6b52c91169e604e941b988b374a10731db7510b7
