### ISSUE TITLE
初始化失败 InjectorService注册自身信息 无法注册

### ISSUE THREAD

**Issue by iswsc** [alipay/SoloPi#56]
E/LauncherApplication: 无法处理 : java.lang.NullPointerException: Attempt to invoke virtual method 'int com.alipay.hulu.common.injector.InjectorService.register(java.lang.Object)' on a null object reference
        at com.alipay.hulu.activity.MyApplication.init(MyApplication.java:257)
        at com.alipay.hulu.common.application.LauncherApplication$1.run(LauncherApplication.java:171)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by cathor01** [comment]
关闭instant run后再进行编译打包

**Comment by iswsc** [comment]
感谢，确实是这个问题
