### ISSUE TITLE
小度1s设备无法使用adb shell来调用

### ISSUE THREAD

**Issue by Sanmejie** [alipay/SoloPi#60]
详细信息如下：`C:\Users\Administrator>adb shell am start -n com.alipay.hulu/.activity.IndexActivity
Starting: Intent { cmp=com.alipay.hulu/.activity.IndexActivity }
Security exception: Permission Denial: starting Intent { flg=0x10000000 cmp=com.alipay.hulu/.activity.IndexActivity } from null (pid=19224, uid=2000) not exported from uid 10038

java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.alipay.hulu/.activity.IndexActivity } from null (pid=19224, uid=2000) not exported from uid 10038
        at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1632)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:438)
        at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:278)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:817)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4778)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:417)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:141)
        at android.os.ShellCommand.exec(ShellCommand.java:96)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:15448)
        at android.os.Binder.shellCommand(Binder.java:594)
        at android.os.Binder.onTransact(Binder.java:492)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4285)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3042)
        at android.os.Binder.execTransact(Binder.java:697)`

**Comment by Sanmejie** [comment]
已经找到原因， 是启动项填错了，  
adb shell am start -n com.alipay.hulu/.activity.SplashActivity
这个是准确的
