### ISSUE TITLE
华为荣耀8权限申请时闪退

### ISSUE THREAD

**Issue by NJ-zero** [alipay/SoloPi#90]
描述：
首次安装，录制回放，权限申请第三步：将solopi 添加至后台白名单中，点击我知道了，白屏，随后闪退

版本：
Android 8.0.0

日志如下：
```
1566524817420,2019.08.23 09:46:57.420,INFO,Soloπ-LauncherApplication,Update activity com.alipay.hulu.activity.SplashActivity to resume state
1566524817753,2019.08.23 09:46:57.753,INFO,Soloπ-InjectorService,启动定时注入!!!
1566524817780,2019.08.23 09:46:57.780,WARN,Soloπ-ClassInfoCache,未配置参数类，可能导致注册失败
1566524817781,2019.08.23 09:46:57.781,WARN,Soloπ-ClassInfoCache,加载参数【stopDisplay】为类型【InjectParam{name='stopDisplay', type=Void}】
1566524817801,2019.08.23 09:46:57.801,WARN,Soloπ-ClassInfoCache,未配置参数类，可能导致注册失败
1566524817801,2019.08.23 09:46:57.801,WARN,Soloπ-ClassInfoCache,加载参数【package】为类型【InjectParam{name='package', type=String}】
1566524817802,2019.08.23 09:46:57.802,WARN,Soloπ-ClassInfoCache,未配置参数类，可能导致注册失败
1566524817802,2019.08.23 09:46:57.802,WARN,Soloπ-ClassInfoCache,加载参数【packageChildren】为类型【InjectParam{name='packageChildren', type=List}】
1566524817803,2019.08.23 09:46:57.803,WARN,Soloπ-ClassInfoCache,未配置参数类，可能导致注册失败
1566524817803,2019.08.23 09:46:57.803,WARN,Soloπ-ClassInfoCache,加载参数【pid】为类型【InjectParam{name='pid', type=ProcessInfo}】
1566524817804,2019.08.23 09:46:57.804,WARN,Soloπ-ClassInfoCache,未配置参数类，可能导致注册失败
1566524817804,2019.08.23 09:46:57.804,WARN,Soloπ-ClassInfoCache,加载参数【pidChildren】为类型【InjectParam{name='pidChildren', type=List}】
1566524817804,2019.08.23 09:46:57.804,WARN,Soloπ-ClassInfoCache,未配置参数类，可能导致注册失败
1566524817805,2019.08.23 09:46:57.805,WARN,Soloπ-ClassInfoCache,加载参数【uid】为类型【InjectParam{name='uid', type=Integer}】
1566524817805,2019.08.23 09:46:57.805,WARN,Soloπ-ClassInfoCache,未配置参数类，可能导致注册失败
1566524817806,2019.08.23 09:46:57.806,WARN,Soloπ-ClassInfoCache,加载参数【puid】为类型【InjectParam{name='puid', type=String}】
1566524817806,2019.08.23 09:46:57.806,WARN,Soloπ-ClassInfoCache,未配置参数类，可能导致注册失败
1566524817807,2019.08.23 09:46:57.807,WARN,Soloπ-ClassInfoCache,加载参数【topActivity】为类型【InjectParam{name='topActivity', type=String}】
1566524819261,2019.08.23 09:46:59.261,INFO,Soloπ-InjectorService,消息【InjectParam{name='app', type=String}::String@2d##1】注入成功
1566524819263,2019.08.23 09:46:59.263,INFO,Soloπ-InjectorService,消息【InjectParam{name='appName', type=String}::String@a37d8##2】注入成功
1566524820210,2019.08.23 09:47:00.210,INFO,Soloπ-LauncherApplication,Update activity com.alipay.hulu.activity.SplashActivity to pause state
1566524824295,2019.08.23 09:47:04.295,WARN,Soloπ-BaseActivity,Activity: IndexActivity, 等待Launcher初始化耗时: 0ms
1566524824308,2019.08.23 09:47:04.308,INFO,Soloπ-PatchRequest,Start request patch list on: https://raw.githubusercontent.com/alipay/SoloPi/master/arm64-v8a.json
1566524824317,2019.08.23 09:47:04.317,INFO,Soloπ-LauncherApplication,Update activity com.alipay.hulu.activity.IndexActivity to resume state
1566524824439,2019.08.23 09:47:04.439,INFO,Soloπ-PermissionDialog,权限弹窗Stop
1566524824740,2019.08.23 09:47:04.740,INFO,Soloπ-LauncherApplication,Update activity com.alipay.hulu.activity.SplashActivity to destroy state
1566524824959,2019.08.23 09:47:04.959,INFO,Soloπ-PatchRequest,接收patch列表PatchResponse{status='success', reason='', version=1, data=[DataBean{name='hulu_imageCompare', url='https://raw.githubusercontent.com/alipay/SoloPi/master/plugins/hulu_imageCompare_v8a.zip', version=7.0, type='base'}, DataBean{name='hulu_screenRecord', url='https://raw.githubusercontent.com/alipay/SoloPi/master/plugins/hulu_screenRecord_v8a.zip', version=7.0, type='required'}, DataBean{name='minicap', url='https://raw.githubusercontent.com/alipay/SoloPi/master/plugins/hulu_minicap.v8a.zip', version=3.0, type='base'}]}
1566524824968,2019.08.23 09:47:04.968,INFO,Soloπ-PatchRequest,安装基础依赖插件： hulu_imageCompare, 版本号：7.000000
1566524824972,2019.08.23 09:47:04.972,INFO,Soloπ-PatchRequest,安装基础依赖插件： minicap, 版本号：3.000000
1566524825348,2019.08.23 09:47:05.348,INFO,Soloπ-InjectorService,启动定时注入!!!
1566524825408,2019.08.23 09:47:05.408,WARN,Soloπ-ClassInfoCache,未配置参数类，可能导致注册失败
1566524825408,2019.08.23 09:47:05.408,WARN,Soloπ-ClassInfoCache,加载参数【package】为类型【InjectParam{name='package', type=String}】
1566524825408,2019.08.23 09:47:05.408,WARN,Soloπ-ClassInfoCache,未配置参数类，可能导致注册失败
1566524825409,2019.08.23 09:47:05.409,WARN,Soloπ-ClassInfoCache,加载参数【packageChildren】为类型【InjectParam{name='packageChildren', type=List}】
1566524825409,2019.08.23 09:47:05.409,WARN,Soloπ-ClassInfoCache,未配置参数类，可能导致注册失败
1566524825409,2019.08.23 09:47:05.409,WARN,Soloπ-ClassInfoCache,加载参数【pid】为类型【InjectParam{name='pid', type=ProcessInfo}】
1566524825409,2019.08.23 09:47:05.409,WARN,Soloπ-ClassInfoCache,未配置参数类，可能导致注册失败
1566524825410,2019.08.23 09:47:05.410,WARN,Soloπ-ClassInfoCache,加载参数【pidChildren】为类型【InjectParam{name='pidChildren', type=List}】
1566524825410,2019.08.23 09:47:05.410,WARN,Soloπ-ClassInfoCache,未配置参数类，可能导致注册失败
1566524825410,2019.08.23 09:47:05.410,WARN,Soloπ-ClassInfoCache,加载参数【uid】为类型【InjectParam{name='uid', type=Integer}】
1566524825410,2019.08.23 09:47:05.410,WARN,Soloπ-ClassInfoCache,未配置参数类，可能导致注册失败
1566524825411,2019.08.23 09:47:05.411,WARN,Soloπ-ClassInfoCache,加载参数【puid】为类型【InjectParam{name='puid', type=String}】
1566524825411,2019.08.23 09:47:05.411,WARN,Soloπ-ClassInfoCache,未配置参数类，可能导致注册失败
1566524825411,2019.08.23 09:47:05.411,WARN,Soloπ-ClassInfoCache,加载参数【topActivity】为类型【InjectParam{name='topActivity', type=String}】
1566524825416,2019.08.23 09:47:05.416,WARN,Soloπ-ClassInfoCache,未配置参数类，可能导致注册失败
1566524825417,2019.08.23 09:47:05.417,WARN,Soloπ-ClassInfoCache,加载参数【stopDisplay】为类型【null】
1566524825854,2019.08.23 09:47:05.854,INFO,Soloπ-InjectorService,消息【InjectParam{name='app', type=String}::String@2d##1】注入成功
1566524825855,2019.08.23 09:47:05.855,INFO,Soloπ-InjectorService,消息【InjectParam{name='appName', type=String}::String@a37d8##2】注入成功
1566524827596,2019.08.23 09:47:07.596,WARN,Soloπ-AssetsManager,Get file costs: 2621
1566524830599,2019.08.23 09:47:10.599,WARN,Soloπ-AssetsManager,Get file costs: 5628
1566524833360,2019.08.23 09:47:13.360,INFO,Soloπ-LauncherApplication,Update activity com.alipay.hulu.activity.IndexActivity to pause state
1566524841339,2019.08.23 09:47:21.339,INFO,Soloπ-InstallReceiver,卸载了 :String@5fd339f##27
1566524842078,2019.08.23 09:47:22.078,INFO,Soloπ-InstallReceiver,安装了 :String@5fd339f##27
1566524844845,2019.08.23 09:47:24.845,INFO,Soloπ-InstallReceiver,卸载了 :String@eecb6307##30
1566524845046,2019.08.23 09:47:25.046,INFO,Soloπ-InstallReceiver,安装了 :String@eecb6307##30
1566524852417,2019.08.23 09:47:32.417,INFO,Soloπ-CmdTools,Socket connecting...
1566524852428,2019.08.23 09:47:32.428,INFO,Soloπ-CmdTools,Socket connected
1566524852429,2019.08.23 09:47:32.429,INFO,Soloπ-CmdTools,ADB connecting...
1566524854769,2019.08.23 09:47:34.769,INFO,Soloπ-CmdTools,ADB connected
1566524869515,2019.08.23 09:47:49.515,INFO,Soloπ-InstallReceiver,卸载了 :String@a6fe1395##23
1566524869540,2019.08.23 09:47:49.540,INFO,Soloπ-LauncherApplication,Update activity com.alipay.hulu.activity.IndexActivity to resume state
1566524869542,2019.08.23 09:47:49.542,INFO,Soloπ-LauncherApplication,Update activity com.alipay.hulu.activity.IndexActivity to pause state
1566524869583,2019.08.23 09:47:49.583,WARN,Soloπ-BaseActivity,Activity: NewRecordActivity, 等待Launcher初始化耗时: 0ms
1566524869628,2019.08.23 09:47:49.628,ERROR,Soloπ-HuluCrashHandler,Unable to start activity ComponentInfo{com.alipay.hulu/com.alipay.hulu.activity.NewRecordActivity}: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 : java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alipay.hulu/com.alipay.hulu.activity.NewRecordActivity}: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 <br> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3303) <br> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411) <br> 	at android.app.ActivityThread.-wrap12(Unknown Source:0) <br> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994) <br> 	at android.os.Handler.dispatchMessage(Handler.java:108) <br> 	at android.os.Looper.loop(Looper.java:166) <br> 	at android.app.ActivityThread.main(ActivityThread.java:7529) <br> 	at java.lang.reflect.Method.invoke(Native Method) <br> 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) <br> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) <br> Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 <br> 	at java.util.ArrayList.get(ArrayList.java:437) <br> 	at com.alipay.hulu.activity.NewRecordActivity.h(SourceFile:321) <br> 	at com.alipay.hulu.activity.NewRecordActivity.onCreate(SourceFile:127) <br> 	at android.app.Activity.performCreate(Activity.java:7383) <br> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218) <br> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256) <br> 	... 9 more <br> 
```

**Comment by cathor01** [comment]
看起来设备上没有安装其他的第三方应用，可以尝试将设置里显示系统应用开关开启
