### ISSUE TITLE
修改用例，步骤中node 节点的 nodeBound 删除内容时，soloPi闪退，空指针异常

### ISSUE THREAD

**Issue by flkxg123** [alipay/SoloPi#96]
故障线程：main
故障日志：
java.lang.NullPointerException: Attempt to get length of null array
	at com.alipay.hulu.a.d.a(SourceFile:215)
	at com.alipay.hulu.a.d$a.afterTextChanged(SourceFile:110)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:9486)
	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:12082)
	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1262)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:574)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:229)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:227)
	at android.text.method.BaseKeyListener.backspaceOrForwardDelete(BaseKeyListener.java:370)
	at android.text.method.BaseKeyListener.backspace(BaseKeyListener.java:71)
	at android.text.method.BaseKeyListener.onKeyDown(BaseKeyListener.java:479)
	at android.text.method.QwertyKeyListener.onKeyDown(QwertyKeyListener.java:362)
	at android.text.method.TextKeyListener.onKeyDown(TextKeyListener.java:141)
	at android.widget.TextView.doKeyDown(TextView.java:7388)
	at android.widget.TextView.onKeyDown(TextView.java:7165)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2713)
	at android.view.View.dispatchKeyEvent(View.java:11852)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1839)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1839)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1839)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1839)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1839)
	at android.widget.ScrollView.dispatchKeyEvent(ScrollView.java:414)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1839)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1839)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1839)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1839)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1839)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1839)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1839)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1839)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1839)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:487)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1865)
	at android.app.Dialog.dispatchKeyEvent(Dialog.java:853)
	at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(SourceFile:59)
	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(SourceFile:319)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:385)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5241)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5109)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4590)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4650)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4609)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4762)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4617)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4819)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4590)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4650)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4609)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4617)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4590)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7280)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7254)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7215)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4355)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:197)
	at android.app.ActivityThread.main(ActivityThread.java:7022)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:515)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)

**Comment by soloPi** [comment]
will fix in next release

**Comment by cathor01** [comment]
fixed in 8cf8676e447e8d8c5b3b310f408a69ee7dec9a1b
